config/routes.rb
Rails.application.routes.draw do
  patch 'banners/complete'
  post 'banners/preview'
  resources :banners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: %i[ show edit update destroy ]

  # GET /banners or /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1 or /banners/1.json
  def show
  end

  def complete
  end

  def preview
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners or /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: "Banner was successfully created." }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1 or /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to @banner, notice: "Banner was successfully updated." }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1 or /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: "Banner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banner_params
      params.require(:banner).permit(:alt_text, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_with(model: banner, local: true, url: "/banners/preview", method: "POST") do |form| %>
  <% if banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
        <% banner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :alt_text %>
    <%= form.text_field :alt_text %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/banners/complete.html.erb
<h1>complete</h1>
<%= link_to 'Index Page', banners_path %>

app/views/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banners</h1>

<table>
  <thead>
    <tr>
      <th>Alt text</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.alt_text %></td>
        <td><%= banner.image %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Back', banners_path %>

app/views/banners/preview.html.erb
<h1>preview</h1>
<%= form_with( local: true, url: "/banners/complete", method: "PATCH") do |form| %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '送信', 'complete' %> |
<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alt text:</strong>
  <%= @banner.alt_text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @banner.image %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BannerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>